### ISSUE TITLE
SUGGESTION: Add NASA GIBS

### ISSUE THREAD

**Issue by PedroVenancio** [opengeos/qgis-basemaps#13]
Dear @giswqs 

Thank you very much for this new repository! Another great contribution for the GIS community!

I leave this suggestion to WMS list, from NASA (NASA's Global Imagery Browse Services):
https://nasa-gibs.github.io/gibs-api-docs/gis-usage/#qgis

It contain a huge amount of data, from several satellites and programs, at global scale and with the possibility to use the temporal component to get access to the historical data. 

Best regards!
Pedro

**Comment by giswqs** [comment]
Good suggestion. It has been added in #14
