### ISSUE TITLE
SUGGESTION: add maps.eox.at to the list

### ISSUE THREAD

**Issue by Scartography** [opengeos/qgis-basemaps#7]
Add free EOxCloudless Sentinel-2 (and other layers) global map tiles. Noncommercial usage is ok here. If you have questions feel free to reach me here or via petr.sevcik@eox.at 

The WMTS or WMS should be quite easy to add.

* Website: https://maps.eox.at/
* WMTS URL: https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml
* WMS URL: https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities
* (EOX company URL: https://eox.at)

**Comment by giswqs** [comment]
Thank you for the suggestion. EOX maps have been added.
